### PR TITLE
Code review request for the apple clone project

### PR DESCRIPTION
**Pull request by patriciachrysy**
Apple product page clone with HTML and CSS(Find the original here: https://web.archive.org/web/20140301004610/http://www.apple.com/ ). Passed the linters and the w3 validation, waiting for review for merging

### CODE REVIEW

**Review by fatymahmed — COMMENTED** [review]
### Hi @patriciachrysy,
Your project looks good 👏👏, however, there are few things you need to fix to make it look better.

**Navbar**
- The navbar should contain the Apple logo and the search icon, but yours aren't being displayed.
screenshot

**Bottom**
- The four elements which are four images in a row should be links just like in the original apple page. 

**General**
 - Your Pull Request should have a short description, see [screenshot of requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png).

[OPTIONAL]
- If you reduce the `font-size `of your footer, it'll look more like the apple page.
- You could use the `<main>` tag for the dominant content of the `<body>` of the document.
- In your README file, under `Getting Started` section, you have `This is an example ...`, you could remove this part

**Review by fatymahmed — CHANGES_REQUESTED** [review]
### Kindly make the suggested changes and request for another code review
## Status: Changes Required
_Feel free to reach out to me on slack(Fatima) if you have any questions, I'd be happy to help._

**Comment by patriciachrysy** [comment]
Solved the icons issue, put links on the products images and made the optional changes

**Comment by izaiasneto4** [comment]
### Hi @patriciachrysy. Good job on correcting the required changes, there's just one thing left. ⬇️ 

- [ ] Please, create a descriptive pull request message as required by @fatymahmed. 

#### That's it! When finished with the required changes please send the code for a new review 🙏 

TSE: Izaias Neto

**Comment by shshamim63** [comment]
## Status :heavy_check_mark: Approved :heavy_check_mark: 
___
Hi @patriciachrysy :wave: ,
You have covered all the changes asked by the previous reviewer. Repository contains a descriptive readme. PR contains a summary. Items are rendering on the places where they should. So awesome job :clap: 
___
### This :+1: is from me, you can go ahead and merge it.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

**Pull request merged**
